version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: zLw473vAW8ELDkV
      RABBITMQ_DEFAULT_PASS: QyuhTTLOCOWfdFu
      RABBITMQ_DEFAULT_VHOST: "/"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
  #  mongo:
  #    image: mongo:latest
  #    container_name: mongodb
  #    environment:
  #      MONGO_INITDB_ROOT_USERNAME: admin
  #      MONGO_INITDB_ROOT_PASSWORD: password
  #    ports:
  #      - "27017:27017"
  #    volumes:
  #      - mongo-data:/data/db
  #  mongo-express:
  #    image: mongo-express:latest
  #    container_name: mongo-express
  #    environment:
  #      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
  #      ME_CONFIG_MONGODB_ADMINPASSWORD: password
  #      ME_CONFIG_MONGODB_SERVER: mongo
  #    ports:
  #      - "8081:8081"
  #    depends_on:
  #      - mongo
  db20m2:
    container_name: db20m2
    image: postgres:alpine
    environment:
      POSTGRES_DB: db20m2
      POSTGRES_USER: zLw473vAW8ELDkV
      POSTGRES_PASSWORD: QyuhTTLOCOWfdFu
      PGDATA: /data/postgres
    volumes:
      - ./db20m2data:/data/postgres
    expose:
      - "5435"
    ports:
      - "5435:5435"
    command: -p 5435
    restart: always
  db20m2event:
    container_name: db20m2event
    image: postgres:alpine
    environment:
      POSTGRES_DB: db20m2event
      POSTGRES_USER: WU8lVfADRqrOCFc
      POSTGRES_PASSWORD: 6pGKe4PXo88bk2i
      PGDATA: /data/postgresevent
    volumes:
      - ./db20m2dataeventi:/data/postgresevent
    expose:
      - "5436"
    ports:
      - "5436:5436"
    command: -p 5436
    restart: always
  db20m2restaurant:
    container_name: db20m2restaurant
    image: postgres:alpine
    environment:
      POSTGRES_DB: db20m2restaurant
      POSTGRES_USER: ItXNrDG1fNRQ4yd
      POSTGRES_PASSWORD: o3YOUyfQH1kFq0
      PGDATA: /data/postgresrestaurant
    volumes:
      - ./db20m2datarestaurant:/data/postgresrestaurant
    expose:
      - "5437"
    ports:
      - "5437:5437"
    command: -p 5437
    restart: always
  db20m2communication:
    container_name: db20m2communication
    image: postgres:alpine
    environment:
      POSTGRES_DB: db20m2communication
      POSTGRES_USER: TIJE0nNlxmqSKxm
      POSTGRES_PASSWORD: o3YOUyfQH1kFq0
      PGDATA: /data/postgrescommunication
    volumes:
      - ./db20m2communication:/data/postgrescommunication
    expose:
      - "5438"
    ports:
      - "5438:5438"
    command: -p 5438
    restart: always
  pgadmin20m2:
    container_name: pgadmin20m2
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: amati.angelo90@gmail.com
      PGADMIN_DEFAULT_PASSWORD: EM6MbK55bpHUtgVN
    depends_on:
      - db20m2
      - db20m2event
      - db20m2restaurant
    ports:
      - "5050:80"

#  discovery-server:
#    image: amatiangelo1990/20m2:discovery-server
#    container_name: discovery-server
#    ports:
#      - "8761:8761"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    depends_on:
#      - zipkin
#  api-gw:
#    image: amatiangelo1990/20m2:api-gw
#    container_name: api-gw
#    ports:
#      - "8088:8088"
#    expose:
#      - "8088"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=TRACE
#    depends_on:
#      - zipkin
#      - discovery-server
#  auth-service:
#    image: amatiangelo1990/20m2:auth-service
#    container_name: auth-service
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=TRACE
#    depends_on:
#      - zipkin
#      - discovery-server
#      - api-gw
#  notification-service:
#    image: amatiangelo1990/20m2:notification-service
#    container_name: notification-service
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=TRACE
#    depends_on:
#      - zipkin
#      - discovery-server
#      - api-gw
#      - mongo
#  ventimetri-service:
#    image: amatiangelo1990/20m2:ventimetri-service
#    container_name: ventimetri-service
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=TRACE
#    depends_on:
#      - zipkin
#      - discovery-server
#      - api-gw
#      - notification-service
#      - db20m2
#  eventi-service:
#    image: amatiangelo1990/20m2:eventi-service
#    container_name: eventi-service
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=TRACE
#    depends_on:
#      - zipkin
#      - discovery-server
#      - api-gw
#      - notification-service
#      - db20m2event
#  restaurant-service:
#    image: amatiangelo1990/20m2:restaurant-service
#    container_name: restaurant-service
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=TRACE
#    depends_on:
#      - zipkin
#      - discovery-server
#      - api-gw
#      - notification-service
#      - db20m2
#      - db20m2restaurant



volumes:
  mongo-data:
    driver: local
  data: {}
  pg_data:
  rabbitmq_data:
  rabbitmq_log:
#networks:
#  default:
#    driver: bridge
#networks:
#  db20m2:
