version: "3.8"
services:
  postgres:
    image: postgres:alpine
    container_name: postgresql_orders
    environment:
      POSTGRES_DB: ventimetri_postgresql
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - db_network
    volumes:
      - pg_data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - postgres
    ports:
      - "5050:80"
    networks:
      - db_network
  mongodb:
    image: mongo
    container_name: mongodb_product
    ports:
      - "27017:27017"
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
      - MONGO_INITDB_DATABASE=product
    networks:
      - mongodb_network
  mongo-express:
    image: mongo-express
    container_name: mongodb_product_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - mongodb_network

volumes:
  data: {}
  pg_data:

networks:
  mongodb_network:
  db_network:
