package com.ventimetriquadriconsulting.restaurant.manage_restaurant.employee.entity.utils_enum;

public enum JobDescription {
    AMMINISTRATORE,
    ADDETTA_AL_MARKETING,
    ADDETTO_ALL_ACCOGLIENZA_CLIENTI,
    AIUTO_BARMAN,
    AIUTO_CUOCO,
    ADD_ALLA_CUCINA,
    AIUTO_CAMERIERE,
    BARMAN,
    CAMERIERE_DI_BAR,
    CAMERIERE,
    CUOCO,
    CUOCO_DI_RISTORANTE,
    COORDINATRICE_DI_SALA,
    COMMIS_DI_CUCINA,
    DIRETTRICE_SALA_DEHORS,
    FOOD_AND_BEVERAGE_MANAGER,
    LAVAPIATTI,
    PASTICCIERE,
    PIZZAIOLO,
    RESPONSABILE_DI_SALA,
    TECNICI_WEB;
}
